version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: database_ignite
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: ignite
      POSTGRES_DB: rentx
    volumes:
      - pgdata:/data/postgres
    # network_mode: host
  # app:
  #   container_name: rentx_api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   working_dir: /usr/app
  #   network_mode: host

volumes:
  pgdata:
  driver_data:
    driver: local
